# Single build and deploy path for the API. Context MUST be repo root.
# Trigger: set _REGION and _GCS_BUCKET (e.g. in trigger substitution vars).
# Do NOT set "Directory" on the trigger; leave source at repo root.

substitutions:
  _SERVICE_NAME: modgen-api
  _REGION: europe-west2
  _GCS_BUCKET: ""  # Set in Cloud Build trigger (e.g. ${PROJECT_ID}-modgen-artifacts)

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/api/Dockerfile
      - -t
      - gcr.io/${PROJECT_ID}/modgen-api:${COMMIT_SHA}
      - .

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=gcr.io/${PROJECT_ID}/modgen-api:${COMMIT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --set-env-vars=GCS_BUCKET=${_GCS_BUCKET},GCP_PROJECT=${PROJECT_ID},CLOUD_RUN_REGION=${_REGION},BUILDER_JOB_NAME=mod-builder
      - --set-secrets=DATABASE_URL=database-url:latest
      - --service-account=modgen-api@${PROJECT_ID}.iam.gserviceaccount.com
      - --allow-unauthenticated
      - --project=${PROJECT_ID}

images:
  - gcr.io/${PROJECT_ID}/modgen-api:${COMMIT_SHA}
