steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-f",
        "apps/api/Dockerfile",
        "-t",
        "gcr.io/$PROJECT_ID/modgen-api:$COMMIT_SHA",
        "."
      ]

images:
  - "gcr.io/$PROJECT_ID/modgen-api:$COMMIT_SHA"
