/**
 * Plane 3: Fabric scaffolding for Tier 1 only.
 * fabric.mod.json, ModMain.java with item and block registries.
 * Optional ExecutionPlan per item → custom item classes (e.g. lightning wand).
 * No creative tabs beyond default, no mixins, no events.
 */

import type { ExpandedSpecTier1 } from "@themodgenerator/spec";
import type { MaterializedFile } from "./types.js";
import type { ExecutionPlan } from "../execution-plan.js";
import { getItemClassNameForRegistration } from "./behavior-generator.js";

function toClassName(s: string): string {
  return s
    .split(/[-_]/)
    .map((p) => (p ? p[0].toUpperCase() + p.slice(1).toLowerCase() : ""))
    .join("");
}

function escapeJson(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

function escapeJava(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function buildGradle(modId: string): string {
  return `plugins {
	id 'java'
	id 'fabric-loom' version '1.7-SNAPSHOT'
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	mavenCentral()
	maven { url = "https://maven.fabricmc.net/" }
}

loom {
	splitEnvironmentSourceSets()
	mods {
		"${modId}" {
			sourceSet("main")
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:\${project.minecraft_version}"
	mappings "net.fabricmc:yarn:\${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:\${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:\${project.fabric_version}"
}

processResources {
	inputs.property "version", project.version
	filteringCharset "UTF-8"
	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
	withSourcesJar()
}
`;
}

function gradleProperties(): string {
  return `# Fabric 1.21.1
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.9
fabric_version=0.109.0+1.21.1

mod_version=1.0.0
maven_group=net.themodgenerator
archives_base_name=generated

org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.configureondemand=false
org.gradle.jvmargs=-Xms64m -Xmx256m
`;
}

function settingsGradle(modId: string): string {
  return `pluginManagement {
	repositories {
		maven { url = "https://maven.fabricmc.net/" }
		gradlePluginPortal()
	}
}

rootProject.name = "${modId}"
`;
}

function fabricModJson(modId: string, modName: string, javaPackage: string, className: string): string {
  return `{
  "schemaVersion": 1,
  "id": "${modId}",
  "version": "\${version}",
  "name": "${escapeJson(modName)}",
  "description": "Generated by The Mod Generator",
  "environment": "*",
  "entrypoints": {
    "main": [
      "net.themodgenerator.${javaPackage}.${className}"
    ]
  },
  "depends": {
    "fabricloader": ">=0.16.0",
    "minecraft": "~1.21.1",
    "java": ">=21",
    "fabric-api": "*"
  }
}
`;
}

function toJavaId(id: string): string {
  return id.replace(/-/g, "_");
}

function modMainJava(
  modId: string,
  modName: string,
  javaPackage: string,
  className: string,
  expanded: ExpandedSpecTier1,
  itemPlans?: ExecutionPlan[]
): string {
  const itemRegistrations = expanded.items
    .map((item, i) => {
      const plan = itemPlans?.[i];
      const itemClassName = getItemClassNameForRegistration(item.id, plan);
      return `		Registry.register(Registries.ITEM, Identifier.of(MOD_ID, "${item.id}"), new ${itemClassName}(new Item.Settings()));`;
    })
    .join("\n");
  const blockLines: string[] = [];
  for (const block of expanded.blocks) {
    const varName = toJavaId(block.id) + "Block";
    blockLines.push(`		Block ${varName} = Registry.register(Registries.BLOCK, Identifier.of(MOD_ID, "${block.id}"), new Block(AbstractBlock.Settings.create()));`);
    blockLines.push(`		Registry.register(Registries.ITEM, Identifier.of(MOD_ID, "${block.id}"), new BlockItem(${varName}, new Item.Settings()));`);
  }
  const blockRegistrations = blockLines.join("\n");

  const hasItems = expanded.items.length > 0;
  const hasBlocks = expanded.blocks.length > 0;
  const imports: string[] = [
    "package net.themodgenerator." + javaPackage + ";",
    "",
    "import net.fabricmc.api.ModInitializer;",
    "import net.minecraft.block.AbstractBlock;",
    "import net.minecraft.block.Block;",
    "import net.minecraft.item.BlockItem;",
    "import net.minecraft.item.Item;",
    "import net.minecraft.registry.Registries;",
    "import net.minecraft.registry.Registry;",
    "import net.minecraft.util.Identifier;",
    "import org.slf4j.Logger;",
    "import org.slf4j.LoggerFactory;",
    "",
  ];
  const initBody: string[] = [];
  if (hasItems) initBody.push(itemRegistrations);
  if (hasBlocks) initBody.push(blockRegistrations);
  initBody.push("		LOGGER.info(\"" + escapeJava(modName) + " initialized.\");");

  const body = [
    "public class " + className + " implements ModInitializer {",
    "	public static final String MOD_ID = \"" + modId + "\";",
    "	public static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);",
    "",
    "	@Override",
    "	public void onInitialize() {",
    ...initBody,
    "	}",
    "}",
  ];

  return imports.join("\n") + "\n" + body.join("\n") + "\n";
}

function mixinsJson(modId: string): string {
  return `{
  "required": true,
  "package": "net.themodgenerator.${modId.replace(/-/g, "_")}.mixin",
  "compatibilityLevel": "JAVA_21",
  "mixins": [],
  "injectors": {
    "defaultRequire": 1
  }
}
`;
}

export interface FabricScaffoldOptions {
  /** When provided, custom item classes (e.g. lightning wand) are registered per plan. */
  itemPlans?: ExecutionPlan[];
}

/**
 * Generate Fabric scaffolding files (build, fabric.mod.json, ModMain, mixins).
 * Deterministic; same expanded + options → same output.
 * When itemPlans[i] requires custom behavior, ModMain registers that custom class.
 */
export function fabricScaffoldFiles(
  expanded: ExpandedSpecTier1,
  options?: FabricScaffoldOptions
): MaterializedFile[] {
  const modId = expanded.spec.modId;
  const modName = expanded.spec.modName;
  const javaPackage = modId.replace(/-/g, "_");
  const className = toClassName(modId) + "Mod";
  const itemPlans = options?.itemPlans;

  const files: MaterializedFile[] = [
    { path: "build.gradle", contents: buildGradle(modId) },
    { path: "gradle.properties", contents: gradleProperties() },
    { path: "settings.gradle", contents: settingsGradle(modId) },
    {
      path: "src/main/resources/fabric.mod.json",
      contents: fabricModJson(modId, modName, javaPackage, className),
    },
    {
      path: `src/main/java/net/themodgenerator/${javaPackage}/${className}.java`,
      contents: modMainJava(modId, modName, javaPackage, className, expanded, itemPlans),
    },
    {
      path: `src/main/resources/${modId}.mixins.json`,
      contents: mixinsJson(modId),
    },
  ];
  return files;
}
